### ISSUE TITLE
TypeError: Cannot assign to read only property 'id' of 0

### ISSUE THREAD

**Issue by WeeJeWel** [sqmk/huejay#74]
Pretty simple error catched when doing a `client.scenes.getAll()`

```
TypeError: Cannot assign to read only property 'id' of 0
    at /node_modules/huejay/lib/Command/Scene/GetScenes.js:27:30
    at Array.map (native)
    at /node_modules/huejay/lib/Command/Scene/GetScenes.js:26:36
```

The weird part is, it's happening on one of my project user's device, but I tested with him and this was the catched error.

**Comment by kixeye-opensource** [comment]
Interesting. I'll see if I can reproduce.

**Comment by sqmk** [comment]
I can investigate. Can your project user post what version his/her bridge API is?

**Comment by jeroenbos22** [comment]
That user is me :). My Api version is 1.16.0 (Hue bridge v1).

**Comment by jeroenbos22** [comment]
Ok, while searching for the version number I noticed my json looked weird. Had a lot of scenes version 1 that didnt exist anymore. Did a cleanup of the hub and now there are only v2 scenes and now it works again! So think it has to do with the V1 scenes since the error state: Cannot assign to read only property 'id' of 0. 0, the first scene was a non existing V1 scene.

So for me it works now but could be helpfull for other users with V1 scenes.

**Comment by sqmk** [comment]
Interesting. Perhaps the older scenes didn't have "id" property then. Good to know! Thanks for checking in.

**Comment by WeeJeWel** [comment]
@sqmk Maybe you can add a check so it doesn't crash, though?
