### ISSUE TITLE
Can not discover bridges using nupnp

### ISSUE THREAD

**Issue by mstfldmr** [sqmk/huejay#75]
discover() function can not discover bridges using the default nupnp strategy. Though, it can discover with upnp strategy.

`# node -v
v4.4.0`

**Comment by kixeye-opensource** [comment]
Are there any specific errors returned from the library itself when using nupnp?

Nupnp results come straight from Philips external apis, so if your bridge doesn't connect to Philips (internet connectivity issues, Firewall, etc), or the IP your node library connects with is different than what your bridge is connecting from, Philips will not return any bridges to you. Upnp is all local, so I am not surprised that strategy will find your bridges.

I'm going to close this unless there are nodejs errors you can share. Otherwise, nupnp is not guaranteed to return results to you depending on your network configuration.

**Comment by sqmk** [comment]
Are there any specific errors returned from the library itself when using nupnp?

Nupnp results come straight from Philips external apis, so if your bridge doesn't connect to Philips (internet connectivity issues, Firewall, etc), or the IP your node library connects with is different than what your bridge is connecting from, Philips will not return any bridges to you. Upnp is all local, so I am not surprised that strategy will find your bridges.

What I can do is change the default strategy to "all" for discovery, so that nupnp and upnp are both used. Nupnp is not guaranteed to return results to you depending on your network configuration, as is upnp.

**Comment by mstfldmr** [comment]
No, there are no error messages. It simply returns null.

**Comment by sqmk** [comment]
This is now defaulted to 'all' in 1.6.0.
